common/models/ValuesInvestments.php
<?php

namespace common\models;

use Yii;
use omgdef\multilingual\MultilingualBehavior;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "values_investments".
 *
 * @property int $id
 * @property int|null $classes_id
 * @property string $name
 * @property string|null $content
 * @property string|null $image
 * @property string|null $created_at
 *
 * @property ClassesInvestments $classes
 * @property ValuesInvestmentsTranslation[] $valuesInvestmentsTranslations
 */
class ValuesInvestments extends MultilingualActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'values_investments';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['classes_id'], 'integer'],
            [['name'], 'required'],
            [['content'], 'string'],
            [['created_at'], 'safe'],
            [['name'], 'string', 'max' => 128],
            [['image'], 'string', 'max' => 255],
            [['classes_id'], 'exist', 'skipOnError' => true, 'targetClass' => ClassesInvestments::className(), 'targetAttribute' => ['classes_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return $this->localizedAttributes([
            'id'                => 'ID',
            'classes_id'        => 'Класс инвестиции',
            'name'              => 'Название',
            'content'           => 'Контент',
            'image'             => 'Изображение',
            'created_at'        => 'Дата создания',
        ]);
    }

    /**
     * @return array
     */
    public function behaviors()
    {
        return ArrayHelper::merge(parent::behaviors(), [
            'MultilingualBehavior' => [
                'class'         => MultilingualBehavior::className(),
                'langClassName' => ValuesInvestmentsTranslation::className(),
                'tableName'     => ValuesInvestmentsTranslation::tableName(),
                'attributes'    => ['name', 'content'],
            ],
        ]);
    }

    public function beforeSave($insert)
    {
        $this->created_at    = Yii::$app->formatter->asDate(time(), 'Y-MM-dd H:i');

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * Gets query for [[Classes]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getClasses()
    {
        return $this->hasOne(ClassesInvestments::className(), ['id' => 'classes_id']);
    }

    /**
     * Gets query for [[ValuesInvestmentsTranslations]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getValuesInvestmentsTranslations()
    {
        return $this->hasMany(ValuesInvestmentsTranslation::className(), ['id' => 'id']);
    }

    public function path()
    {
        return Yii::getAlias('@backend') . '/web/uploads/images/values-investments/';
    }

    public function getImage()
    {
        return ($this->image) ? '/backend/web/uploads/images/values-investments/' . $this->image : '';
    }
}

backend/controllers/ValuesInvestmentsController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\ValuesInvestments;
use backend\models\search\ValuesInvestmentsSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use backend\controllers\BackendController;
use common\models\MultilingualActiveRecord;

/**
 * ValuesInvestmentsController implements the CRUD actions for ValuesInvestments model.
 */
class ValuesInvestmentsController extends BackendController
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all ValuesInvestments models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ValuesInvestmentsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single ValuesInvestments model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new ValuesInvestments model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new ValuesInvestments();

        if ($model->load(Yii::$app->request->post())) {
            $this->createImage($model);

            if ($model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing ValuesInvestments model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $oldImage = $model->image;

        if ($model->load(Yii::$app->request->post())) {
            $this->updateImage($model, $oldImage);

            if ($model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing ValuesInvestments model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Deletes image an existing ValuesInvestments model.
     * If deletion is successful, the browser will be redirected to the 'form' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDeleteImage($id)
    {
        $model = $this->findModel($id);

        $this->deleteImage($model);

        if ($model->save(false)) {
            return $this->redirect(['update?id=' . $id]);
        }
    }

    /**
     * Finds the ValuesInvestments model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        /* @var $activeRecord MultilingualActiveRecord */

        $model = ValuesInvestments::find()->multilingual()->where(['id' => $id])->one();

        if (null === $model) {
            throw new NotFoundHttpException('Указанная страница не найдена.');
        }

        return $model;
    }
}

backend/views/values-investments/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\file\FileInput;
use mihaildev\ckeditor\CKEditor;
use mihaildev\elfinder\ElFinder;
use common\models\ClassesInvestments;

/* @var $this yii\web\View */
/* @var $model common\models\ValuesInvestments */
/* @var $form yii\widgets\ActiveForm */
?>


<div class="values-investments-form">

    <?php $form = ActiveForm::begin(); ?>
    <div class="col-md-12 pl-0 pr-0">
        <div class="form-group" style="float: right;margin-top:7px;">
            <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
        </div>
        <ul id="myTab" role="tablist" class="nav nav-tabs">
            <li class="nav-item active">
                <a id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true" class="nav-link active">Общие</a>
            </li>
            <? foreach (\common\models\i18n::locales() as $locale) : ?>
                <? if (Yii::$app->language <> $locale) : ?>
                    <li class="nav-item">
                        <a id="<?= $locale ?>-tab" data-toggle="tab" href="#lang-<?= $locale ?>" role="tab" aria-controls="<?= $locale ?>" aria-selected="false" class="nav-link"><?= $locale ?></a>
                    </li>
                <? endif; ?>
            <? endforeach; ?>
        </ul>
        <div id="myTabContent" class="tab-content bg-white box-shadow p-4 mb-4">
            <? foreach (\common\models\i18n::locales() as $locale) : ?>
                <? if (Yii::$app->language <> $locale) : ?>
                    <div id="lang-<?= $locale ?>" role="tabpanel" aria-labelledby="<?= $locale ?>-tab" class="tab-pane fade">

                        <?= $form->field($model, 'name_' . $locale)->textInput(['maxlength' => true]) ?>
                        <? if (!$model->isNewRecord) : ?>
                            <admin-component :classs="'content-<?= $locale ?>'" :array='<?= ($model->{'content_' . $locale}) ?>'></admin-component>
                        <? else : ?>
                            <admin-component :classs="'content-<?= $locale ?>'" :array="[]"></admin-component>
                        <? endif; ?>

                        <?= $form->field($model, 'content_' . $locale)->textInput(['type' => "hidden", 'class' => 'content_' . $locale])->label(false) ?>
                    </div>
                <? endif; ?>
            <? endforeach; ?>

            <div id="home" role="tabpanel" aria-labelledby="home-tab" class="tab-pane fade show active in">

                <?= $form->field($model, 'classes_id')->dropDownList(ClassesInvestments::getList()) ?>

                <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

                <? if (!$model->isNewRecord) : ?>
                    <admin-component :classs="'content-ru'" :array='<?= $model->content ?>'></admin-component>
                <? else : ?>
                    <admin-component :classs="'content-ru'" :array='[]'></admin-component>
                <? endif; ?>

                <?= $form->field($model, 'content')->textInput(['type' => 'hidden', 'class' => "content_ru"])->label(false) ?>

                <?= $form->field($model, 'image')->widget(FileInput::classname(), [
                    'pluginOptions' => [
                        'showUpload'            => false,
                        'initialPreview'        => $model->isNewRecord ? '' : $model->getImage(),
                        'initialPreviewAsData'  => true,
                        'initialCaption'        => $model->isNewRecord ? '' : $model->image,
                        'showRemove'            => true,
                        'deleteUrl'             => \yii\helpers\Url::to(['/values-investments/delete-image', 'id' => $model->id]),
                    ], 'options' => ['accept' => 'image/*'],
                ]); ?>

            </div>
        </div>
    </div>

    <div class=" form-group">
        <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
    </div>


    <?php ActiveForm::end(); ?>

</div>
<script>
    document.querySelector(' [type="submit" ]').addEventListener('click', function(e) {
        e.preventDefault();
        let contentArray = [];
        <? foreach (\common\models\i18n::locales() as $locale) : ?>
            <? if (Yii::$app->language <> $locale) : ?>
                let content<?= $locale ?> = [];
                document.querySelectorAll('.content-' + '<?= $locale ?>').forEach(input => {
                    content<?= $locale ?>.push(input.value);
                    console.log(content<?= $locale ?>);
                });
                document.querySelector('.content_' + '<?= $locale ?>').value = JSON.stringify(content<?= $locale ?>);
            <? endif; ?>
        <? endforeach; ?>
        document.querySelectorAll('.content-ru').forEach(input => {
            contentArray.push(input.value);
        });
        document.querySelector('.content_ru').value = JSON.stringify(contentArray);
        document.getElementById('w0').submit();
    });
</script>
<style>
    .fc-0 {
        display: flex;
        flex-wrap: nowrap;
    }
</style>

backend/views/values-investments/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\search\ValuesInvestmentsSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="values-investments-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'classes_id') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'content') ?>

    <?= $form->field($model, 'image') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/values-investments/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\ValuesInvestments */

$this->title = 'Создание Значение инвестиции';
$this->params['breadcrumbs'][] = ['label' => 'Значение инвестиции', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="values-investments-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/values-investments/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
use common\models\ClassesInvestments;
use common\models\ValuesInvestments;
use yii\helpers\ArrayHelper;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\search\ValuesInvestmentsSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Значение инвестиции';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="values-investments-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Создать', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php Pjax::begin(); ?>
    <?php // echo $this->render('_search', ['model' => $searchModel]); 
    ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            [
                'attribute' => 'classes_id',
                'filter'    => ClassesInvestments::getList(),
                'value' => function ($model) {
                    return
                        Html::a($model->classes->title, ['/classes-investments/view', 'id' => $model->classes->id]);
                },
                'format' => 'raw',
            ],
            'name',
            [
                'format' => 'html',
                'attribute' => 'image',
                'value' => function ($model) {
                    return Html::img($model->getImage(), ['width' => 100]);
                }
            ],

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>

    <?php Pjax::end(); ?>

</div>

backend/views/values-investments/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\ValuesInvestments */

$this->title = 'Редактировать : ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Значение инвестиции', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Редактирование';
?>
<div class="values-investments-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/values-investments/view.php
<?php

use yii\helpers\Html;
use common\widgets\MultilingualDetailView;

/* @var $this yii\web\View */
/* @var $model common\models\ValuesInvestments */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Значение инвестиции', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="values-investments-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Редактировать', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Удалить', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Вы действительно хотите удалить этот элемент?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= MultilingualDetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            [
                'attribute' => 'classes_id',
                'value' => function ($model) {
                    return
                        Html::a($model->classes->title, ['/classes-investments/view', 'id' => $model->classes->id]);
                },
                'format' => 'raw',
            ],
            'name',
            'content:ntext',
            [
                'format' => 'html',
                'attribute' => 'image',
                'value' => function ($model) {
                    return Html::img($model->getImage(), ['width' => 100]);
                }
            ],
            'created_at',
        ],
    ]) ?>

</div>