common/models/Banner.php
<?php

namespace common\models;

use Yii;
use omgdef\multilingual\MultilingualBehavior;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "banner".
 *
 * @property int $id
 * @property int|null $menu_id
 * @property string|null $title
 * @property string|null $image
 * @property string|null $video
 * @property int|null $status
 * @property string|null $created_at
 *
 * @property Menu $menu
 * @property BannerTranslation[] $bannerTranslations
 */
class Banner extends MultilingualActiveRecord
{
    const STATUS_IMAGE         = 1;
    const STATUS_VIDEO         = 2;
    const STATUS_DISABLED       = 0;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'banner';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['menu_id', 'status'], 'integer'],
            [['created_at'], 'safe'],
            [['title'], 'string'],
            [['image', 'video'], 'string', 'max' => 255],
            [['menu_id'], 'exist', 'skipOnError' => true, 'targetClass' => Menu::className(), 'targetAttribute' => ['menu_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return $this->localizedAttributes([
            'id'            => 'ID',
            'menu_id'       => 'Меню',
            'title'         => 'Заголовок',
            'image'         => 'Изображение',
            'video'         => 'Видео',
            'status'        => 'Статус',
            'created_at'    => 'Дата создания',
        ]);
    }

    public function beforeSave($insert)
    {
        $this->created_at    = Yii::$app->formatter->asDate(time(), 'Y-MM-dd H:i');

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * @return array
     */
    public function behaviors()
    {
        return ArrayHelper::merge(parent::behaviors(), [
            'MultilingualBehavior' => [
                'class'         => MultilingualBehavior::className(),
                'langClassName' => BannerTranslation::className(),
                'tableName'     => BannerTranslation::tableName(),
                'attributes'    => ['title'],
            ],
        ]);
    }

    /**
     * @return array
     */
    public static function statuses()
    {
        return [
            self::STATUS_IMAGE     => 'image',
            self::STATUS_VIDEO     => 'video',
            self::STATUS_DISABLED   => 'disabled',
        ];
    }

    /**
     * @return array
     */
    public static function statusDescription()
    {
        return [
            self::STATUS_IMAGE      => 'изображение',
            self::STATUS_VIDEO      => 'видео',
            self::STATUS_DISABLED   => 'закрытый',
        ];
    }

    /**
     * Gets query for [[Menu]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getMenu()
    {
        return $this->hasOne(Menu::className(), ['id' => 'menu_id']);
    }

    /**
     * Gets query for [[BannerTranslations]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getBannerTranslations()
    {
        return $this->hasMany(BannerTranslation::className(), ['id' => 'id']);
    }

    public function path()
    {
        return Yii::getAlias('@backend') . '/web/uploads/images/banner/';
    }

    public function getImage()
    {
        return ($this->image) ? '/backend/web/uploads/images/banner/' . $this->image : '';
    }

    public function getPathVideo()
    {
        return Yii::getAlias('@backend') . '/web/uploads/video/banner/';
    }

    public function getVideo()
    {
        return ($this->video) ? '/backend/web/uploads/video/banner/' . $this->video : '';
    }

    public static function getBanner($menu_id)
    {
        return self::find()->where(['menu_id' => $menu_id])->orderBy(['id' => SORT_ASC])->one();
    }

    public static function getMain()
    {
        return self::find()->where(['menu_id' => 1])->orderBy(['id' => SORT_ASC])->one();
    }

    public static function getAbout()
    {
        return self::find()->where(['menu_id' => 2])->orderBy(['id' => SORT_ASC])->one();
    }

    public static function getInvestment()
    {
        return self::find()->where(['menu_id' => 3])->orderBy(['id' => SORT_ASC])->one();
    }

    public static function getInformationCentre()
    {
        return self::find()->where(['menu_id' => 4])->orderBy(['id' => SORT_ASC])->one();
    }

    public static function getCareer()
    {
        return self::find()->where(['menu_id' => 5])->orderBy(['id' => SORT_ASC])->one();
    }

    public static function getMap()
    {
        return self::find()->where(['menu_id' => 6])->orderBy(['id' => SORT_ASC])->one();
    }
}

backend/controllers/BannerController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\Banner;
use backend\models\search\BannerSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use backend\controllers\BackendController;
use common\models\MultilingualActiveRecord;

/**
 * BannerController implements the CRUD actions for Banner model.
 */
class BannerController extends BackendController
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Banner models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new BannerSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Banner model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Banner model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Banner();

        if ($model->load(Yii::$app->request->post())) {
            $this->createImage($model);
            $this->createVideo($model);

            if($model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Banner model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $oldImage = $model->image;
        $oldVideo = $model->video;

        if ($model->load(Yii::$app->request->post())) {
            $this->updateImage($model, $oldImage);
            $this->updateVideo($model, $oldVideo);

            if($model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Banner model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Deletes image an existing Banner model.
     * If deletion is successful, the browser will be redirected to the 'form' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
    */
    public function actionDeleteImage($id)
    {
        $model = $this->findModel($id);

        $this->deleteImage($model);

        if($model->save(false)){
        return $this->redirect(['update?id='.$id]);
        }
    }

    /**
     * Finds the Banner model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        /* @var $activeRecord MultilingualActiveRecord */

        $model = Banner::find()->multilingual()->where(['id' => $id])->one();

        if (null === $model) {
        throw new NotFoundHttpException('Указанная страница не найдена.');
        }

        return $model;
    }
}

backend/views/banner/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\file\FileInput;
use common\models\Banner;
use common\models\Menu;
use mihaildev\ckeditor\CKEditor;
use mihaildev\elfinder\ElFinder;

/* @var $this yii\web\View */
/* @var $model common\models\Banner */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="banner-form">

    <?php $form = ActiveForm::begin(); ?>

    <div class="col-md-12 pl-0 pr-0">
        <div class="form-group" style="float: right;margin-top:7px;">
            <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
        </div>
        <ul id="myTab" role="tablist" class="nav nav-tabs">
            <li class="nav-item active">
                <a id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true" class="nav-link active">Общие</a>
            </li>
            <? foreach (\common\models\i18n::locales() as $locale) : ?>
                <? if (Yii::$app->language <> $locale) : ?>
                    <li class="nav-item">
                        <a id="<?= $locale?>-tab" data-toggle="tab" href="#lang-<?= $locale?>" role="tab" aria-controls="<?= $locale?>" aria-selected="false" class="nav-link"><?= $locale?></a>
                    </li>
                <? endif; ?>
            <? endforeach; ?>
        </ul>
        <div id="myTabContent" class="tab-content bg-white box-shadow p-4 mb-4">
            <? foreach (\common\models\i18n::locales() as $locale) : ?>
                <? if (Yii::$app->language <> $locale) : ?>
                    <div id="lang-<?= $locale?>" role="tabpanel" aria-labelledby="<?= $locale?>-tab" class="tab-pane fade">

                        <?= $form->field($model, 'title_'.$locale)->widget(CKEditor::className(), [
                            'editorOptions' => ElFinder::ckeditorOptions('elfinder', [
                                'preset' => 'full',    // basic, standard, full
                                'inline' => false,      //по умолчанию false
                            ])
                        ]); ?>

                    </div>
                <? endif; ?>
            <? endforeach; ?>

            <div id="home" role="tabpanel" aria-labelledby="home-tab" class="tab-pane fade show active in">

                <?= $form->field($model, 'menu_id')->dropDownList(Menu::getList()) ?>

<!--                --><?//= $form->field($model, 'status')->dropDownList(Banner::statusDescription()) ?>

                <?= $form->field($model, 'title')->widget(CKEditor::className(), [
                    'editorOptions' => ElFinder::ckeditorOptions('elfinder', [
                        'preset' => 'full',    // basic, standard, full
                        'inline' => false,      //по умолчанию false
                    ])
                ]); ?>

<!--                --><?//= $form->field($model, 'image')->widget(FileInput::classname(), [
//                    'pluginOptions' => [
//                        'showUpload'            => false ,
//                        'initialPreview'        => $model->isNewRecord ? '' : $model->getImage(),
//                        'initialPreviewAsData'  => true,
//                        'initialCaption'        => $model->isNewRecord ? '': $model->image,
//                        'showRemove'            => true ,
//                        'deleteUrl'             => \yii\helpers\Url::to(['/banner/delete-image', 'id'=> $model->id]),
//                    ] ,
//                    'options' => ['accept' => 'image/*'],
//                ]); ?>

<!--                --><?php
//                echo $form->field($model, 'video')->widget(FileInput::classname(), [
//                    'pluginOptions' => [
//                        'showUpload' => false ,
//                    ] ,
//                    'options' => ['accept' => 'video/*'],
//                ]);
//                ?>

            </div>

        </div>
    </div>

    <div class="form-group">
        <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/banner/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\search\BannerSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="banner-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'menu_id') ?>

    <?= $form->field($model, 'title') ?>

    <?= $form->field($model, 'image') ?>

    <?= $form->field($model, 'video') ?>

    <?php // echo $form->field($model, 'status') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/banner/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Banner */

$this->title = 'Создание Баннер';
$this->params['breadcrumbs'][] = ['label' => 'Баннер', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="banner-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/banner/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
use common\models\Banner;
use yii\helpers\ArrayHelper;
use common\models\Menu;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\search\BannerSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Баннер';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="banner-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Создать', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php Pjax::begin(); ?>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            [
                'attribute' => 'menu_id',
                'filter'    => Menu::getList(),
                'value' => function ($model) {
                    return
                        Html::a($model->menu->title, ['/menu/view', 'id' => $model->menu->id]);
                },
                'format' => 'raw',
            ],
            [
                'format' => 'raw',
                'attribute' => 'title',
                'value' => function($model){
                    return $model->title;
                }
            ],
//            [
//                'format' => 'html',
//                'attribute' => 'image',
//                'value' => function($model){
//                    return Html::img($model->getImage(), ['width'=>100]);
//                }
//            ],
//            [
//                'attribute' => 'status',
//                'filter' => Banner::statusDescription(),
//                'value' => function ($model) {
//                    return ArrayHelper::getValue(Banner::statusDescription(), $model->status);
//                },
//                'format' => 'raw',
//            ],
            //'status',
            //'created_at',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>

    <?php Pjax::end(); ?>

</div>

backend/views/banner/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Banner */

$this->title = 'Редактировать Баннер: ' . $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Баннер', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Редактирование';
?>
<div class="banner-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/banner/view.php
<?php

use yii\helpers\Html;
use common\widgets\MultilingualDetailView;
use common\models\Banner;
use yii\helpers\ArrayHelper;

/* @var $this yii\web\View */
/* @var $model common\models\Banner */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Баннер', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="banner-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Редактировать', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Удалить', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Вы действительно хотите удалить этот элемент?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= MultilingualDetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            [
                'attribute' => 'menu_id',
                'value' => function ($model) {
                    return
                        Html::a($model->menu->title, ['/menu/view', 'id' => $model->menu->id]);
                },
                'format' => 'raw',
            ],
            'title',
//            [
//                'format' => 'html',
//                'attribute' => 'image',
//                'value' => function($model){
//                    return Html::img($model->getImage(), ['width'=>100]);
//                }
//            ],
//            'video',
//            [
//                'attribute' => 'status',
//                'filter' => Banner::statusDescription(),
//                'value' => function ($model) {
//                    return ArrayHelper::getValue(Banner::statusDescription(), $model->status);
//                },
//                'format' => 'raw',
//            ],
            'created_at',
        ],
    ]) ?>

</div>